pager: pager.c
	gcc -o pager pager.c
wordgen: wordgen.c
	gcc -o wordgen wordgen.c
wordsearch: wordsearch.c
	gcc -o wordsearch wordsearch.c
launcher: launcher.c
	gcc -o launcher launcher.c
clean:
	find . -maxdepth 1 -type f ! -name "Makefile" ! -name "makefile" ! -name "*.*" -delete
